### PR TITLE
Replacing the drop-down component in MaterialPager with a text box

### PR DESCRIPTION
**Pull request by saso5**
Optimizing MaterialPager performance by removing the drop-down component and replacing it with a text box. This also improves UX with tables with more than 10 pages as scrolling thru the list of pages is not so efficient.

### CODE REVIEW

**Comment by BenDol** [comment]
Thanks for the contribution, will review it soon.

**Comment by saso5** [comment]
Hey @BenDol, what seems to be the holdup whit this PR?

**Comment by BenDol** [comment]
Sorry, business on my end. Will merge this now.

**Comment by saso5** [comment]
Did not see your secound part of the comment. Is the branch still relevant?

**Comment by kevzlou7979** [comment]
Duplicate https://github.com/GwtMaterialDesign/gwt-material-table/pull/128

**Pull request closed without merging**
